version: '3'

services:
  gogs:
    container_name: gogs
    restart: always
    image: gogs/gogs:latest
    ports:
        - "3022:22"
        - "3000:3000"
    expose:
      - "3000"
    volumes:
        - gogs_app:/data
        - gogs_logs:/app/gogs/log
    environment:
        - "RUN_CROND=true"
    networks:
      - emp-network
    depends_on:
      - gogs-db

  gogs-db:
    container_name: gogs_db
    image: postgres:latest
    networks:
      - emp-network
    environment:
        POSTGRES_DB: gogs
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        PGDATA: /var/lib/postgresql/data
        POSTGRES_HOST: gogs-db
        POSTGRES_PORT: 5432
    volumes:
        - db_data:/var/lib/postgresql/data

volumes:
    gogs_app:
      driver: local
      driver_opts:
          type: none
          device: ./gogs/app
          o: bind
    gogs_logs:
      driver: local 
      driver_opts:
        type: none
        device: ./gogs/logs
        o: bind
    db_data:
      driver: local
      driver_opts:
          type: none
          device: ./gogs/db_data
          o: bind

networks: 
  emp-network:
    driver: bridge