apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "orchestration-portal.fullname" . }}
  labels:
    {{- include "orchestration-portal.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "orchestration-portal.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "orchestration-portal.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "orchestration-portal.fullname" . }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
