apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "orchestration-portal.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "orchestration-portal.labels" . | nindent 4 }}
spec:
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "orchestration-portal.fullname" . }}
                port:
                  number: {{ .Values.service.port }}