# permissions for end users to view solutions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: solution-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: orchestration-operator
    app.kubernetes.io/part-of: orchestration-operator
    app.kubernetes.io/managed-by: kustomize
  name: solution-viewer-role
rules:
- apiGroups:
  - solution.symphony
  resources:
  - solutions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - solution.symphony
  resources:
  - solutions/status
  verbs:
  - get
