apiVersion: solution.symphony/v1
kind: Instance
metadata:
  labels:
    app.kubernetes.io/name: instance
    app.kubernetes.io/instance: instance-sample
    app.kubernetes.io/part-of: orchestration-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: orchestration-operator
  name: instance-sample
spec:
  # TODO(user): Add fields here
