replicaCount: 1

image:
  repository: ghcr.io/pdpresson/apps/hello-world
  pullPolicy: IfNotPresent

service:
  port: 9080

env:
  APP_GREETING: "unset"
  APP_TARGET: "unset"

ingress:
  path: /
  hostname: edge.local